# docker compose -f docker-compose-environment.yml up -d
# docker compose -f docker-compose-environment.yml down -v
# docker compose -f docker-compose-app.yml -f docker-compose-environment.yml down --volumes --remove-orphans --rmi all

services:
  big-market-mysql:
    image: mysql:8.0.32
    container_name: big-market-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Los_Angeles
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: big_market # Added to create the database on startup
    networks:
      - big-market-network
    ports:
      - "13306:3306"
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - big-market-mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 15s

  big-market-phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: big-market-phpmyadmin
    hostname: big-market-phpmyadmin
    ports:
      - "8899:80"
    environment:
      - PMA_HOST=big-market-mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=password
    depends_on:
      big-market-mysql:
        condition: service_healthy
    networks:
      - big-market-network

  big-market-redis:
    image: redis:6.2
    container_name: big-market-redis
    restart: always
    hostname: big-market-redis
    privileged: true
    ports:
      - "16379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - big-market-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  big-market-redis-admin:
    image: spryker/redis-commander:0.8.0
    container_name: big-market-redis-admin
    hostname: big-market-redis-commander
    restart: always
    ports:
      - "18081:8081"
    environment:
      - REDIS_HOSTS=local:big-market-redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
      - LANG=C.UTF-8
      - LANGUAGE=C.UTF-8
      - LC_ALL=C.UTF-8
    networks:
      - big-market-network
    depends_on:
      big-market-redis:
        condition: service_healthy

  big-market-rabbitmq:
    image: rabbitmq:3.12.9
    container_name: big-market-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    command: rabbitmq-server
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - big-market-network

networks:
  big-market-network:
    driver: bridge
    name: big-market-network

volumes:
  big-market-mysql-data:
    name: big-market-mysql-data