services:
  big-market-app:
    image: boboboboo/big-market-app:2.1
    container_name: big-market-app
    restart: always
    ports:
      - "8091:8091"
    environment:
      - TZ=America/Los_Angeles
      - SERVER_PORT=8091
      - APP_CONFIG_API_VERSION=v1
      - APP_CONFIG_CROSS_ORIGIN=*
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:mysql://big-market-mysql:3306/big_market?serverTimezone=UTC&characterEncoding=utf8&autoReconnect=true
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_HIKARI_POOL_NAME=Retail_HikariCP
      - REDIS_SDK_CONFIG_HOST=big-market-redis
      - REDIS_SDK_CONFIG_PORT=6379
    volumes:
      - ./log:/data/log
    networks:
      - big-market-network
    depends_on:
      - big-market-mysql
      - big-market-redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  big-market-front-app:
    container_name: big-market-front-app
    image: boboboboo/big-market-front-app:2.1
    restart: always
    networks:
      - big-market-network
    ports:
      - "3000:3000"
    environment:
      - API_HOST_URL=http://luckydraw.hebo.life # This should be your public-facing backend URL
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://0.0.0.0:3000/" ]
      interval: 1m
      timeout: 10s
      retries: 3